### ISSUE TITLE
How do i use this??

### ISSUE THREAD

**Issue by iiAbady** [prashantkoshta/heroku-command-vscode#5]
How do i use this??, I've a nodejs project and I wonder how is this addon works?

**Comment by sktzofrenic** [comment]
Hit ctrl+shit+p to open the command pallete and then start typing `git push...` and it will allow you to push to the heroku remote inside VSCode. Also you can type heroku commands by typing `herok...` and commands will autocomplete for you.

**Comment by jblazer1** [comment]
Not working.  I open the command pallete and choose heroku login I get a new terminal labeled heroku.  Then I open the command pallete again and choose heroku login and nothing happens.  Then I open the command pallete again and choose heroku create and I get bash: heroku: command not found.  What am I doing wrong?

**Comment by sktzofrenic** [comment]
You need to have the heroku CLI  installed already. Did you do that?

https://devcenter.heroku.com/articles/heroku-cli

**Comment by DOdeveloper** [comment]
HI.  Yes I did that.  I can use it through the powershell terminal outside of vs code but my trouble occurs when I try to use inside vs code.  I installed and reloaded but have not been able to perform any commands from within vs code.

**Comment by skelesp** [comment]
I have exactly the same problem. Heroku CLI is working in powershell and cmd, but in VScode I get the "bash: heroku: command not found" error in the terminal which opens automatically when I run a Heroku command in vscode.

Any progress on this issue?

**Comment by zebfross** [comment]
So the problem for me was with VS Code.  It looks like environment variables (like PATH) don't update even after restarting the app.  I'm sure there is an easier fix, but restarting my computer worked to update the PATH variable in vs code.
